// Code generated by scripts/ci/gen_error_codes.py from api/openapi.yaml. DO NOT EDIT.

export const ErrorCodes = {
  E_BAD_REQUEST: { http: 400, code: 40001 },
  E_UNAUTHENTICATED: { http: 401, code: 40101 },
  E_INVALID_CREDENTIALS: { http: 401, code: 40102 },
  E_FORBIDDEN: { http: 403, code: 40301 },
  E_PASSWORD_CHANGE_REQUIRED: { http: 403, code: 40302 },
  E_CSRF_FAILED: { http: 403, code: 40303 },
  E_NOT_FOUND: { http: 404, code: 40401 },
  E_STATE_CONFLICT: { http: 409, code: 40901 },
  E_DS_REFERENCED: { http: 409, code: 40902 },
  E_IDEMPOTENCY_KEY_REUSED: { http: 409, code: 40903 },
  E_IDEMPOTENCY_IN_PROGRESS: { http: 409, code: 40904 },
  E_NAME_EXISTS: { http: 409, code: 40905 },
  E_PRECONDITION_FAILED: { http: 412, code: 41201 },
  E_VALIDATION_FAILED: { http: 422, code: 42201 },
  E_TARGET_NOT_ALLOWED: { http: 422, code: 42202 },
  E_PARAM_MUTUALLY_EXCLUSIVE: { http: 422, code: 42203 },
  E_PARAM_REQUIRED_ONE: { http: 422, code: 42204 },
  E_PARAM_NAME_MISMATCH: { http: 422, code: 42205 },
  E_WEAK_PASSWORD: { http: 422, code: 42206 },
  E_PRECONDITION_REQUIRED: { http: 428, code: 42801 },
  E_RATE_LIMITED: { http: 429, code: 42901 },
  E_ACCOUNT_LOCKED: { http: 429, code: 42902 },
  E_DM_UNAVAILABLE: { http: 502, code: 50201 },
  E_SOURCE_UNREACHABLE: { http: 502, code: 50202 },
  E_TARGET_AUTH_FAILED: { http: 502, code: 50203 },
} as const;

export type ErrorCodeName = keyof typeof ErrorCodes;

export const FieldErrorCodes = [
  "E_FIELD_REQUIRED",
  "E_PARAM_RANGE",
  "E_PARAM_ENUM",
  "E_PARAM_REGEX",
  "E_PARAM_DEPENDENCY",
  "E_FIELD_EXISTENCE",
] as const;

export const PrecheckCodes = [
  "PRECHECK_TABLE_CONFLICT",
  "PRECHECK_PK_CONFLICT",
  "PRECHECK_ROUTE_OVERLAP",
  "PRECHECK_TASK_NAME_DUP",
  "PRECHECK_CHARSET_TZ_MISMATCH",
] as const;
