#!/usr/bin/env python3
"""Generate TS/Go error-code constants from the OpenAPI single source of truth.

Hard gate (reviewer G2): if `FieldError.errorCode` lacks an `enum`, or the enum
does not match the `x-field-error-codes` / `x-precheck-codes` registries, this
script exits non-zero instead of silently emitting an empty set.

Canonical destinations (repo skeleton, do not move):
  frontend/src/api/errorCodes.ts      # generated, DO NOT EDIT
  backend/internal/apierr/codes.go    # generated, DO NOT EDIT

Usage:
  python scripts/ci/gen_error_codes.py                       # write both defaults
  python scripts/ci/gen_error_codes.py --ts <p> --go <p>     # override outputs
  python scripts/ci/gen_error_codes.py --stdout              # print TS only

CI runs this (no args) then `git diff --exit-code` to catch drift.
"""
import argparse
import os
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SPEC = ROOT / "api" / "openapi.yaml"
DEFAULT_TS = ROOT / "frontend" / "src" / "api" / "errorCodes.ts"
DEFAULT_GO = ROOT / "backend" / "internal" / "apierr" / "codes.go"

HEADER = "// Code generated by scripts/ci/gen_error_codes.py from api/openapi.yaml. DO NOT EDIT.\n\n"


def load(path):
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def precheck_codes(doc):
    out = []
    for item in doc.get("x-precheck-codes", []):
        out.append(item["code"] if isinstance(item, dict) else item)
    return out


def collect(doc):
    """Validate and return (envelope_codes, field_codes, precheck)."""
    field_codes = doc.get("x-field-error-codes") or []
    precheck = precheck_codes(doc)
    if not field_codes:
        raise SystemExit("FAIL: x-field-error-codes is empty")
    if not precheck:
        raise SystemExit("FAIL: x-precheck-codes is empty")
    enum = (doc["components"]["schemas"]["FieldError"]["properties"]["errorCode"]).get("enum")
    if not enum:
        raise SystemExit("FAIL: FieldError.errorCode.enum missing (reviewer G2 gate)")
    expected = set(field_codes) | set(precheck)
    if set(enum) != expected:
        missing = sorted(expected - set(enum))
        extra = sorted(set(enum) - expected)
        raise SystemExit(f"FAIL: FieldError.errorCode.enum mismatch; missing={missing} extra={extra}")
    return doc.get("x-error-codes") or [], field_codes, precheck


def ts_source(envelope, field_codes, precheck):
    lines = [HEADER]
    lines.append("export const ErrorCodes = {\n")
    for c in envelope:
        lines.append(f'  {c["name"]}: {{ http: {c["http"]}, code: {c["code"]} }},\n')
    lines.append("} as const;\n\n")
    lines.append("export type ErrorCodeName = keyof typeof ErrorCodes;\n\n")
    lines.append("export const FieldErrorCodes = [\n")
    for e in field_codes:
        lines.append(f'  "{e}",\n')
    lines.append("] as const;\n\n")
    lines.append("export const PrecheckCodes = [\n")
    for e in precheck:
        lines.append(f'  "{e}",\n')
    lines.append("] as const;\n")
    return "".join(lines)


def go_source(envelope, field_codes, precheck):
    lines = [HEADER, "package apierr\n\n"]
    lines.append("const (\n")
    for c in envelope:
        lines.append(f'\t{c["name"]} = {c["code"]}\n')
    lines.append(")\n\n")
    lines.append("// HTTPStatus maps envelope codes to their authoritative HTTP status.\n")
    lines.append("var HTTPStatus = map[int]int{\n")
    for c in envelope:
        lines.append(f'\t{c["name"]}: {c["http"]},\n')
    lines.append("}\n\n")
    lines.append("var FieldErrorCodes = []string{\n")
    for e in field_codes:
        lines.append(f'\t"{e}",\n')
    lines.append("}\n\n")
    lines.append("var PrecheckCodes = []string{\n")
    for e in precheck:
        lines.append(f'\t"{e}",\n')
    lines.append("}\n")
    return "".join(lines)


def write(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("spec", nargs="?", default=str(DEFAULT_SPEC))
    ap.add_argument("--ts", default=str(DEFAULT_TS))
    ap.add_argument("--go", default=str(DEFAULT_GO))
    ap.add_argument("--stdout", action="store_true", help="print TS to stdout, write nothing")
    args = ap.parse_args()
    envelope, field_codes, precheck = collect(load(args.spec))
    ts = ts_source(envelope, field_codes, precheck)
    if args.stdout:
        sys.stdout.write(ts)
        return 0
    write(args.ts, ts)
    write(args.go, go_source(envelope, field_codes, precheck))
    return 0


if __name__ == "__main__":
    sys.exit(main())
